server:
  port: "8080"
  mode: "debug"  # debug, release
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  database: "lab_recruitment"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  log_level: "info"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-here-change-in-production"
  expire_time: "24h"

log:
  level: "info"  # debug, info, warn, error, fatal
  format: "json"  # json, text
  output: "stdout"  # stdout, logs/app.log
  max_size: 100  # MB
  max_backups: 3
  max_age: 28  # days
  compress: true

upload:
  path: "uploads"
  max_size: 10485760  # 10MB
  allowed_ext: "jpg,jpeg,png,gif,pdf,doc,docx" 